title: Sachin Sulkunte # name definition
logo: "/images/PersonalImage.jpg?raw=true" # photo
description: > # summary section
  Majoring in Computer Engineering at the University of Maryland at College Park with an interest in embedded systems and software development.
  <br>
  <a href="https://www.linkedin.com/in/sachinsulkunte/">View My LinkedIn Profile</a> 
  <br> <br>
  <a href="https://www.github.com/SachinSulkunte/">View My Github Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-192503119-1 # universal tracking tag
