title: Sachin Sulkunte # name definition
logo: "/images/PersonalImage.jpg?raw=true" # photo
description: > # summary section
  University of Maryland at College Park <br>
  Pursuing B.S. in Computer Engineering <br>
  Minor in Robotics and Autonomous Systems <br>
  Advanced Cybersecurity Security Experience for Students Honors Program <br>
  <a href="https://www.linkedin.com/in/sachinsulkunte/">View My LinkedIn Profile</a> 
  <br> <br>
  <a href="https://www.github.com/SachinSulkunte/">View My Github Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-192503119-1 # universal tracking tag
