title: Sachin Sulkunte # name definition
logo: "/images/PersonalImage.jpg?raw=true" # photo
description: > # summary section
  University of Maryland at College Park <br>
  - B.S. Computer Engineering 2024 <br>
  - Minor in Robotics and Autonomous
    Systems <br>
  - Cybersecurity Honors Program <br> <br>
  <a href="https://www.linkedin.com/in/sachinsulkunte/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://www.github.com/SachinSulkunte/">View My Github Profile</a>
theme: jekyll-theme-minimal
