title: Sachin Sulkunte # name definition
logo: "/images/PersonalImage.jpg?raw=true" # photo
description: > # summary section
  First description 
  <br>I am currently a first-year student majoring in Computer Engineering at the University of Maryland at College Park with an interest in embedded systems and robotics.
  Previously, I was involved in several technical internships in which I was able to develop my software and hardware development skills. 
  I aim to gain further experience through summer internships, working alongside professionals in a STEM environment.<br>
  
  <a href="https://www.linkedin.com/in/sachinsulkunte/">My LinkedIn Profile</a> 
  <a href="https://github.com/SachinSulkunte/">My Github Profile</a> 
theme: jekyll-theme-minimal
google_analytics: G-7LZQ6REC5K # analytics tag
